### ISSUE TITLE
Issue with sending SIGHUP to reload nbd server config

### ISSUE THREAD

**Issue by taylorty** [NetworkBlockDevice/nbd#102]
I am using NBD 3.19 version
I tried to reload the nbd server config file by sending SIGHUP to the process. The client is able to setup the connection fine with the server

sudo /usr/local/sbin/nbd-client xxxx -N test1 /dev/nbd1 -b 4096 -persist
Negotiation: ..size = 10240MB
bs=4096, sz=10737418240 bytes

But then when I tried to drive IO using FIO on that device, it complained that it is a 0 size device.
/dev/nbd1: zero sized block device?

The nbd client syslog says

kernel: block nbd1: Connection timed out
kernel: block nbd1: shutting down sockets
kernel: print_req_error: 5 callbacks suppressed
kernel: print_req_error: I/O error, dev nbd1, sector 0

The nbd server syslog says

Connection dropped: Connection reset by peer

Is this a known issue? Is there a workaround for reloading the config file without killing the existing connection?

I appreciate any help in advance.

**Comment by yoe** [comment]
Those log messages actually suggest that it's a middle box which kills the connection: the client says "Connection timed out", the server says "Connection reset by peer".

The current implementation of SIGHUP handling should only add new configurations to the running server, without touching the existing ones. I haven't double-checked, but the logs you show don't suggest the SIGHUP is at fault here.

Can you confirm that it's impossible for you to reproduce this without SIGHUP, and that the disconnect happens immediately after the SIGHUP?

Thanks,

**Comment by taylorty** [comment]
Thank you so much for the response. I tried killing the nbd-server process entirely (without using SIGHUP), then reloading the config and it worked fine. 

Let me clarify the issue more. The existing configurations still work as expected. And the new configurations are able to be added according to the messages but when I issued IO to the connected nbd-client device, the IO would fail and I saw 'Connection dropped: Connection reset by peer' on the server side.

**Comment by yoe** [comment]
Ah! That's a different story; I thought you were connected to the old server, and that that failed to work after adding a new configuration and sending SIGHUP.

I'll have a look at this when next I have some time, thanks.

**Comment by yoe** [comment]
Thanks. Yes, that might be the case.

I was going to say that the tarballs were not that old, but you're right; it's been longer than I thought. I'll look at releasing 3.20 some time soon.

**Comment by kumasam4** [comment]
Hi,
I have NBD Server 3.20 installed on RHEL7 Operating system and configured. While adding new exports under NBD server config, i need to reload new configuration for the exports. While sending SIGHUP signal via OS process to the root PID, it makes NBD-SERVER process dead.
Later, i tried with a few more test attempts with the same SIGHUP signal after NBD-SERVER service restart & re-adding exports under config. Sometimes, it works for a few iterations but later it fails. Currently, i have only 5 exported devices in nbd server config, planned to scale up with multiple exports as per needs.

Please assist or advise any feedback..

**Comment by yoe** [comment]
@kumasam4,

> Hi,
> I have NBD Server 3.20

That means it's not this issue, but another one, as this issue was closed in 3.20.

Please open a new bug report, and make sure it contains any error messages that nbd-server might output upon receiving SIGHUP.

Meanwhile, closing this issue as it should be fixed (even if a similar one may still exist)
