### ISSUE TITLE
autogen.sh Failure: I/O error : Attempt to load network entity

### ISSUE THREAD

**Issue by PhysixProject** [NetworkBlockDevice/nbd#106]
I attempted to compile from release 3.20 tarball and from git repo itself. Both fail with same error. The URL it is trying to download, http://docbook2x.sf.net/latest/xslt/man/docbook.xsl does exist and can be retrieved with wget.

./autogen.sh 
+ make -C man -f mans.mk nbd-server.1.sh.in nbd-server.5.sh.in nbd-client.8.sh.in nbd-trdump.1.sh.in nbdtab.5.sh.in
make: Entering directory '/home/tree/nbd/man'
LC_ALL=C docbook2man nbd-server.1.in.sgml
I/O error : Attempt to load network entity http://docbook2x.sf.net/latest/xslt/man/docbook.xsl
warning: failed to load external entity "http://docbook2x.sf.net/latest/xslt/man/docbook.xsl"
cannot parse http://docbook2x.sf.net/latest/xslt/man/docbook.xsl
Unable to recognise encoding of this document at /usr/lib/perl5/site_perl/5.30.0/XML/SAX/PurePerl/EncodingDetect.pm line 100.
Document requires an element [Ln: 1, Col: 0]
make: *** [mans.mk:12: nbd-server.1.sh.in] Error 255
make: Leaving directory '/home/tree/nbd/man'

**Comment by yoe** [comment]
It probably does not attempt to download anything from the network, but instead tries to parse the DTD, which is supposed to be in the sgml catalog even if it has a web URL. You need to install the docbook DTDs to make that work. Did you do that?

**Comment by PhysixProject** [comment]
I did not. Thanks for your reply. :)

**Comment by yoe** [comment]
Assuming that fixed it, closing this bug. If not, feel free to reopen with more info.
