### ISSUE TITLE
Windows 10 version?

### ISSUE THREAD

**Issue by IBIT-ZEE** [NetworkBlockDevice/nbd#113]
Where can I get a windows version?
I need a Windows version to connect to Linux NBD Client (or to a server Server)...
?anybody knows where to get a Windows port of NBD?

**Comment by yoe** [comment]
For the server side, the server shipped in this repository compiles and works under cygwin, which should be sufficient for most purposes.

For the client side, there is https://github.com/cloudbase/wnbd -- although that project is still fairly new, so it might be a bit rough around the edges perhaps.

Not really an issue in NBD, so closing.

**Comment by mani9876** [comment]
> 
> 
> For the server side, the server shipped in this repository compiles and works under cygwin, which should be sufficient for most purposes.
> 
> For the client side, there is https://github.com/cloudbase/wnbd -- although that project is still fairly new, so it might be a bit rough around the edges perhaps.
> 
> Not really an issue in NBD, so closing.

Hello yoe,
do you know if it should also work to use cygwin with nbd-server to share a physical drive?
I've tried to compile NBD on cygwin, and everything is fine, I can also share files fia nbd-server on Windows, but if I am referencing a physcial drive (SD Card) I get an I/O Error on the Linux Client side, if I try to read the nbd device.

Thanks!

**Comment by yoe** [comment]
On Sun, Apr 11, 2021 at 11:35:47PM -0700, mani9876 wrote:
>      For the server side, the server shipped in this repository compiles and
>      works under cygwin, which should be sufficient for most purposes.
> 
>      For the client side, there is https://github.com/cloudbase/wnbd --
>      although that project is still fairly new, so it might be a bit rough
>      around the edges perhaps.
> 
>      Not really an issue in NBD, so closing.
> 
>    Hello yoe,
>    do you know if it should also work to use cygwin with nbd-server to share
>    a physical drive?

Possibly, if you know how to access the raw device.

>    I've tried to compile NBD on cygwin, and everything is fine, I can also
>    share files fia nbd-server on Windows, but if I am referencing a physcial
>    drive (SD Card) I get an I/O Error on the Linux Client side, if I try to
>    read the nbd device.

Please try compiling nbd-server with the "--enable-debug" option to the
configure script, and reproduce the problem that way. What is the
output?

-- 
     ***@***.***{be,co.za}
wouter@{grep.be,fosdem.org,debian.org}
