### ISSUE TITLE
Build from git not working

### ISSUE THREAD

**Issue by rparkins999** [NetworkBlockDevice/nbd#120]
[ rparkins999/nbd is an unmodified fork from  NetworkBlockDevice/nbd ]
rparkins@rparkins48:~/Documents/LinuxCode/nbd> git remote -v
origin  https://github.com/rparkins999/nbd.git (fetch)
origin  https://github.com/rparkins999/nbd.git (push)
rparkins@rparkins48:~/Documents/LinuxCode/nbd> git checkout
Your branch is up to date with 'origin/master'.
rparkins@rparkins48:~/Documents/LinuxCode/nbd> ./autogen.sh
+ make -C man -f mans.mk nbd-server.1.sh.in nbd-server.5.sh.in nbd-client.8.sh.in nbd-trdump.1.sh.in nbdtab.5.sh.in
make: Entering directory '/home/rparkins/Documents/LinuxCode/nbd/man'
make: 'nbd-server.1.sh.in' is up to date.
make: 'nbd-server.5.sh.in' is up to date.
LC_ALL=C docbook2man nbd-client.8.in.sgml
Using catalogs: /etc/sgml/catalog, /etc/sgml/catalog, /usr/share/sgml/CATALOG.docbook-dsssl-stylesheets
Using stylesheet: /usr/share/sgml/docbook/utils-0.6.14/docbook-utils.dsl#print
Working on: /home/rparkins/Documents/LinuxCode/nbd/man/nbd-client.8.in.sgml
nsgmls:/home/rparkins/Documents/LinuxCode/nbd/man/nbd-client.8.in.sgml:1:59:W: cannot generate system identifier for public text "-//OASIS//DTD DocBook V4.5//EN"
nsgmls:/home/rparkins/Documents/LinuxCode/nbd/man/nbd-client.8.in.sgml:27:0:E: reference to entity "REFENTRY" for which no system identifier could be generated
nsgmls:/home/rparkins/Documents/LinuxCode/nbd/man/nbd-client.8.in.sgml:1:0: entity was defined here
nsgmls:/home/rparkins/Documents/LinuxCode/nbd/man/nbd-client.8.in.sgml:27:0:E: DTD did not contain element declaration for document type name
nsgmls:/home/rparkins/Documents/LinuxCode/nbd/man/nbd-client.8.in.sgml:29:9:E: element "REFENTRY" undefined
nsgmls:/home/rparkins/Documents/LinuxCode/nbd/man/nbd-client.8.in.sgml:30:15:E: element "REFENTRYINFO" undefined

... etc.

Does some other tool need to be installed that you haven't listed?

**Comment by yoe** [comment]
Yes, you need to install the docbook utilities if you want to build from git

**Comment by rparkins999** [comment]
I did install docbook utilities: it still would not build. It seems to require a particular version of docbook utilities, but it doesn't clearly say which. I eventually got it to build by removing the build instructions for the man pages, since I already had those from the installed version. I needed to build it myself in order to make a debuggable version to find the cause of a failure to connect.

    On Thursday, 10 June 2021, 09:07:58 BST, Wouter Verhelst ***@***.***> wrote:  
 
 


Yes, you need to install the docbook utilities if you want to build from git
