### ISSUE TITLE
Multiple nbd device usage.

### ISSUE THREAD

**Issue by edineshkumar** [NetworkBlockDevice/nbd#121]
I am using two different nbd device (/dev/nbd0 and /dev/nbd2) for my application. 
Facing some issue with nbd2 device.

**Does I need to do anything  in between of configuring two nbd devices?**

Why because, I configure one nbd device, then I am using it in user space . Then, if I configure second nbd device, there is no issue.

Whenever, I am  configuring two nbd device at a time, Then, I will face issue with recently configured device.

**Comment by yoe** [comment]
I'm not entirely sure what the question is, but:

If you are using the ioctl() interface for configuring the device, then you you should know that the NBD_DO_IT ioctl does not return until the device is disconnected. This means that your program will "hang" in that ioctl() and will not be able to do anything at all until then.

If you are using the netfilter interface for configuring, then that's a different matter.

Hope this helps; if not, feel free to reopen.
