### ISSUE TITLE
Where to get the patch guarantee swap over TCP and seem to be deadlock-free ?

### ISSUE THREAD

**Issue by LWT-GO** [NetworkBlockDevice/nbd#127]
"swapping over TCP now works , but it requires heavy patches into Linux's network layer."
So, where can I get these patches?

**Comment by yoe** [comment]
This comment on nbd.sourceforge.io is outdated; I'll remove it. Swapping over NBD is safe now.

**Comment by yoe** [comment]
Actually, the comment already no longer appears there. Where did you see that comment? I'd like to remove it wherever you found it.

Thanks,

**Comment by yoe** [comment]
question was asked, but no feedback was received. Closing.
