### ISSUE TITLE
Problems encountered when using network block devices to enable the swap function 

### ISSUE THREAD

**Issue by LWT-GO** [NetworkBlockDevice/nbd#129]
In the process of enabling swap using the network block device, when the system runs for a period of time, it will suddenly freeze. The higher the delay between client and server, the shorter the system uptime. The system log shows "BUG: scheduling while atomic: kswapd0/142/0x00000002", I check the nbd.c file, which uses mutex_lock(&nbd->tx_lock). I don't know if this bug is related to the use of mutex locks. Has anyone encountered this problem?

**Comment by yoe** [comment]
nbd.c is in the kernel, not in the userspace client, which is what this repository is about.

For kernel bugs, please talk to the kernel maintainers.
