### ISSUE TITLE
How to configure a local Ubuntu system to boot from NBD server hosting a multiple partition(e.g. GPT) image

### ISSUE THREAD

**Issue by 593749519** [NetworkBlockDevice/nbd#145]
just as the title saying

**Comment by yoe** [comment]
install nbd-client, and read /use/share/doc/nbd-client/README.Debian

**Comment by 593749519** [comment]
Thanks, that help a lot

**Comment by 593749519** [comment]
Problem solved! The /use/share/doc/nbd-client/README.Debian is great, finally I can make a VM system switch booting from an NBD image on server. Only when expect to auto mount root on NBD image, seems must set linux command line: root=nbd0px which is not clearly mentioned in document, as a newbie, it needs quite an exploring.
