### ISSUE TITLE
Fixes for CentOS 6

### ISSUE THREAD

**Issue by gwyn17** [NetworkBlockDevice/nbd#39]
The included patch allows 3.13 to be compiled on CentOS 6.  The issue is that g_thread_init() was never called in nbd-server.  

I've included a line that should fix this in configure.ac, but I can't test it because CentOS 6 doesn't have recent enough versions of autotools, aclocal etc.  So I copy-pasted the relevant bits into configure.

Also adds includes pthread.h where used.

[Philip_Gwyn-nbd-3.13-g_thread_init-01.patch.txt](https://github.com/yoe/nbd/files/282454/Philip_Gwyn-nbd-3.13-g_thread_init-01.patch.txt)

**Comment by yoe** [comment]
A different fix for this issue has been committed with dace3adbe4b4, so closing.
