### ISSUE TITLE
Protocol does not guarantee data consistency for on-the-fly commands

### ISSUE THREAD

**Issue by yann-morin-1998** [NetworkBlockDevice/nbd#46]
From the protocol description: "The server MAY process commands out
of order". There are a few conditions specified, but nothing about
guarantees given on the ordering of actions performed for commands.

Specifically, there is no guarantee (or lack thereof) expressed about
the consistency of data when two or more commands are on-the-fly, have
overlapping ranges and at least one is a write command (write,
write-zeroes, trim).

So the questions:

1. Is that something that the protocol should specify?

2. What is the behaviour of the reference implementation? What do the
   various clients (Linux, qemu) expect?

Note: two overlapping ranges `A` and `B` can be arranged as such:

    A   [----]  [----]  [----]  [------]  [----]      [----]
    B   [----]  [--]      [--]    [--]      [----]  [----]

**Comment by yoe** [comment]
We discussed that in detail when writing the protocol spec, and decided that to add requirements that clients should not send overlapping commands and that servers should check that would incur difficulties on said servers that would not be worth it.

Perhaps the spec could say that clients SHOULD NOT do so, but that servers MAY ignore the situation if it happens, or some such. At any rate, a client doing so is dabbing into "undefined territory" as it would be known for C constructs, and what happens could be anything.

As for current implementations, the reference implementation (which is only the server really, as the client "just" does the setup) doesn't care about it, the Linux kernel doesn't issue them AFAIK, and neither does qemu.

**Comment by josefbacik** [comment]
Yeah imposing this kind of requirement on the server would be overly burdensome, normal hard drives don't make sure things are done in order.  A properly working linux client won't do this unless some application does it with O_DIRECT with different threads.  We assume that the user is smart enough to make sure this sort of thing doesn't happen, and if the client is a file system this won't ever actually be seen.

**Comment by yann-morin-1998** [comment]
@yoe @josefbacik Thanks for the feedback. :-)

Would like that I send a PR amending the protocol to explicitly say that there is no such guarantee?

**Comment by yoe** [comment]
Better to do that on the mailinglist instead: https://lists.sourceforge.net/lists/listinfo/nbd-general

We usually do some review there before changes to the protocol are accepted, to make sure that no accidental mistakes are made.

**Comment by yann-morin-1998** [comment]
@yoe OK, will do. Thanks for the quick feedback! :-)

Closing the issue now.
