### ISSUE TITLE
postrun isn't called on unclean client disconnections

### ISSUE THREAD

**Issue by alkisg** [NetworkBlockDevice/nbd#47]
If I run `nbd-client server-ip -N swap /dev/nbd5`, and then `killall nbd-client` (or in general disconnect without using nbd-client -d), the server-side postrun action isn't called.

This affects LTSP, which uses the postrun action to clean up NBD swap files:
https://bugs.launchpad.net/ltsp/+bug/1686062
While normally LTSP clients should call `nbd-client -d` on shutdown, there are cases (e.g. connectivity or abrupt client shutdown) where the client doesn't call it.

Please call the postrun action even on SIGPIPE or whenever else the server process realizes that the client has exited.

**Comment by josefbacik** [comment]
This is due to the kernel waiting in a way that cannot be interrupted for the server to disconnect.  It has been fixed in my netlink rework, we will wait with signals enabled so if the nbd-client gets killed we'll clean up properly.

**Comment by yoe** [comment]
@josefbacik It's not, it's a server side issue. When the connection drops, the server is supposed to do cleanup, but as this bug points out, it doesn't always happen... And it should.

**Comment by alkisg** [comment]
Thanks! Could I please also ask a question about a possible workaround for the LTSP case?
What if we modify our prerun script to remove the swap file after 10 seconds:

> \# generate the swap file
> dd if=/dev/zero of="$SWAP" bs=1M count=0 seek="$SIZE"
> \# remove the swap file after 10 seconds;
> \# the kernel won't remove it from disk until nbd-server stops using it
> ( sleep 10; rm -f "$SWAP" ) >/dev/null 2>/dev/null &

This should work as long as nbd-server keeps the file open while it's using it without closing it / reopening it for every single read request. Does it do that?
I tested it and it seems to do what we want...

**Comment by abligh** [comment]
I think you should be fine. That approach is also more race-free. As I understand it using your former approach there is nothing to prevent a reconnect before the swap file is deleted.

> On 26 Apr 2017, at 07:43, Alkis Georgopoulos <notifications@github.com> wrote:
> 
> Thanks! Could I please also ask a question about a possible workaround for the LTSP case?
> What if we modify our prerun script to remove the swap file after 10 seconds:
> 
> # generate the swap file
> dd if=/dev/zero of="$SWAP" bs=1M count=0 seek="$SIZE"
> # remove the swap file after 10 seconds;
> # the kernel won't remove it from disk until nbd-server stops using it
> ( sleep 10; rm -f "$SWAP" ) >/dev/null 2>/dev/null &
> 
> This should work as long as nbd-server keeps the file open while it's using it without closing it / reopening it for every single read request. Does it do that?
> I tested it and it seems to do what we want...
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Alex Bligh

**Comment by josefbacik** [comment]
Sorry I was looking at the nbd-client part of it, my bad.

**Comment by yoe** [comment]
I accidentally pushed a commit that contained something which shouldn't have been in there, so I force-pushed a different commit over it.

Sorry for the mess :-)
