### ISSUE TITLE
tls and tlshuge tests failed during 'make check'

### ISSUE THREAD

**Issue by cheese** [NetworkBlockDevice/nbd#49]
nbd-3.15.2

$ make check
....
./tls
TLS handshake failed: Error in the pull function.

** (process:27332): WARNING **: Could not open socket: Could not read size: Resource temporarily unavailable

** (process:27332): WARNING **: Could not read size: Resource temporarily unavailable

** (process:27332): WARNING **: Could not run test: Could not read size: Resource temporarily unavailable
FAIL: tls
./tlshuge
TLS handshake failed: Error in the pull function.

** (process:27351): WARNING **: Could not open socket: Could not read size: Resource temporarily unavailable

** (process:27351): WARNING **: Could not read size: Resource temporarily unavailable

** (process:27351): WARNING **: Could not run test: Could not read size: Resource temporarily unavailable
FAIL: tlshuge

**Comment by yoe** [comment]
Right. That's because tests/run/certs/client-cert.pem has expired.

I fixed this on master, but forgot to build 3.15.3 off that. I'll look at doing so tonight.

Meanwhile, you need commit 1406502224717ebdebd26d93b2deb824453be4d9

**Comment by yoe** [comment]
I cherry-picked that commit on top of a new branch, and released 3.15.3 off that. This should work again, now.
