### ISSUE TITLE
TRIM/DISCARD is not currently supported on raw block device exports

### ISSUE THREAD

**Issue by dimovnike** [NetworkBlockDevice/nbd#64]
When using discard,i get this error:

> blkdiscard /dev/nbd2       
> blkdiscard: /dev/nbd2: BLKDISCARD ioctl failed: Operation not supported 

How can I enable this feature? Currently I use 4.10.0 kernel.
Thanks.

**Comment by yoe** [comment]
On Fri, Dec 08, 2017 at 11:35:04PM +0000, dimovnike wrote:
> When using discard,i get this error:
> 
>     blkdiscard /dev/nbd2
>     blkdiscard: /dev/nbd2: BLKDISCARD ioctl failed: Operation not supported
> 
> How can I enable this feature? Currently I use 4.10.0 kernel.
> Thanks.

Did you enable the trim setting on the server?

(I have vague plans of making that the default in a future version of the
server, but currently it's not)

-- 
Could you people please use IRC like normal people?!?

  -- Amaya Rodrigo Sastre, trying to quiet down the buzz in the DebConf 2008
     Hacklab

**Comment by dimovnike** [comment]
It was not enabled. It works good after I enabled it. Thanks.

**Comment by dimovnike** [comment]
while it worked correctly in a loop device, it doesn't work  in a ZVOL (zfs virtual volume). The zvol itself supports discard (i.e. the blkdiscard command works when run locally). How to debug this further?

**Comment by dimovnike** [comment]
here is a log file of what happens in server when trim is issued.
[trim.log](https://github.com/NetworkBlockDevice/nbd/files/1598022/trim.log)

It seems that the length is calculated wrong. Can you please check?

**Comment by yoe** [comment]
Yeah, that seems wrong. Had a short look last night, but more investigation is needed.

Which version of the server are you using?

**Comment by dimovnike** [comment]
i was using nbd-3.15.2-114-g00cef30 but I see there are 5 new commits. Is it worth upgrading and testing again?

**Comment by dimovnike** [comment]
hi, are there any news on this issue? thanks.

**Comment by yoe** [comment]
I haven't had time to fix this yet. Patches always welcome, though ;-)

**Comment by qyz** [comment]
For what it's worth, I've run into the same issue. I have an xfs volume on a zvol that I export via nbd-server (version 3.15.2 from Debian Stable). When I run fstrim on the client, it reports success:

```
root@client:/etc# fstrim -v /vol_data01
/vol_data01: 155,6 GiB (167032643584 bytes) trimmed
```

But I can see in the zfs details on the server that the amount of referenced data does not shrink to the reported value. With `strace` on nbd-server I see a lot of calls to `fallocate` which return `EOPNOTSUPP` followed by a lot of calls that return `EINVAL`.

```
[pid 29758] fallocate(3, FALLOC_FL_KEEP_SIZE|FALLOC_FL_PUNCH_HOLE, 29827072, 421888) = -1 EOPNOTSUPP (Operation not supported)
...
[pid 29758] fallocate(3, FALLOC_FL_KEEP_SIZE|FALLOC_FL_PUNCH_HOLE, 286117171200, -196424704000) = -1 EINVAL (Invalid argument)
```

I'd be happy to test patches. 

Cheers,
qyz

**Comment by qyz** [comment]
Zfs does not support fallocate, and that is unlikely to change soon. I have had a look at Qemu and it discards data by calling `ioctl (fd, BLKDISCARD, range)`. Simply replacing the fallocate call with an ioctl call in nbd-server should be simple. But is there a reason why fallocate was chosen in the first place? 

We should probably make this conditional and use autotools to test for the availability of ioctl and BLKDISCARD, right?

**Comment by yoe** [comment]
fallocate works on plain files, the ioctl doesn't. I hadn't thought of the `BLKDISCARD` ioctl when I implemented that, I suppose I should have.

It might make sense for the code to try one and fall back to he other, very much like we do with the `BLKGETSIZE64` ioctl and `fstat()` in nbdsrv.c:size_autodetect. Since that runs fairly often though, perhaps it's better to remember somehow that we're on a block device rather than a plain file, so that we don't try both every time.
