### ISSUE TITLE
3.15 server and 3.17 client compatibility

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [NetworkBlockDevice/nbd#74]
I have an nbd sever 3.15 on debian stable and 3.17 client on debian sid. After some update it become broken. (Unfortunately I don't know the previous version that works before update)
```
# pv /dev/nbd0 > /dev/null
pv: /dev/nbd0: read failed: Input/output error
```
client's dmesg:
```
block nbd0: Connection timed out
block nbd0: shutting down sockets
print_req_error: I/O error, dev nbd0, sector 54784
print_req_error: I/O error, dev nbd0, sector 54528
print_req_error: I/O error, dev nbd0, sector 54528
Buffer I/O error on dev nbd0, logical block 6816, async page read
```
server's syslog:
```
nbd_server[3507]: Read failed: End of file
nbd_server[3507]: Exiting.
nbd_server[1665]: Child exited with 1
```
3.15 client on debian stable works fine.

Should 3.17 client work with 3.15 server or this is correct behavior?

**Comment by yoe** [comment]
This is #66, so closing as duplicate.
