### ISSUE TITLE
Clarify length of NBD_INFO information requests in NBD_OPT_GO/NBD_OPT_INFO

### ISSUE THREAD

**Issue by nhooyr** [NetworkBlockDevice/nbd#85]
See https://github.com/NetworkBlockDevice/nbd/blob/01188597bfd524d5b87d7cf4c818564dd91a4810/doc/proto.md#option-types

> 16 bits x n - list of NBD_INFO information requests

Should be

> 16 bits * number_of_information_requests - list of NBD_INFO information requests

Otherwise its not very clear imo.

**Comment by yoe** [comment]
disagree (and this is a very tiny thing anyway)
