### ISSUE TITLE
HUP-signal can lead to g_thread_pool_set_max_threads(tpool, 0 ...)

### ISSUE THREAD

**Issue by juhaerk** [NetworkBlockDevice/nbd#96]
HUP-signal can lead to use of an uninitialized value of max_threads, setting it to a possible value of 0, leading to nbd-clients hanging right after the negotation process.

Problem seen in 3.15.2 and 3.18. The current master appears to have the same problem (by code inspection).

**Comment by juhaerk** [comment]
Fix is in pull request... https://github.com/NetworkBlockDevice/nbd/pull/97
Very lightly tested yet, but proceeding to testing...

**Comment by yoe** [comment]
fix was merged, so closing.

**Comment by kumasam4** [comment]
Hi,
I have NBD Server 3.20 installed on RHEL7 Operating system and configured. While adding new exports under NBD server config, i need to reload new configuration for the exports. While sending SIGHUP signal via OS process to the root PID, it makes NBD-SERVER process dead.
Later, i tried with a few more test attempts with the same SIGHUP signal after NBD-SERVER service restart & re-adding exports under config. Sometimes, it works for a few iterations but later it fails. Currently, i have only 5 exported devices in nbd server config, planned to scale up with multiple exports as per needs.

Please assist or advise any feedback..
